//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.AdminReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminReference.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddItem", ReplyAction="http://tempuri.org/IAdminService/AddItemResponse")]
        int AddItem(string Name, string Description, float Price, string Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddItem", ReplyAction="http://tempuri.org/IAdminService/AddItemResponse")]
        System.Threading.Tasks.Task<int> AddItemAsync(string Name, string Description, float Price, string Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteItemById", ReplyAction="http://tempuri.org/IAdminService/DeleteItemByIdResponse")]
        int DeleteItemById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteItemById", ReplyAction="http://tempuri.org/IAdminService/DeleteItemByIdResponse")]
        System.Threading.Tasks.Task<int> DeleteItemByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditItem", ReplyAction="http://tempuri.org/IAdminService/EditItemResponse")]
        int EditItem(int Id, string Name, string Description, float Price, string Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditItem", ReplyAction="http://tempuri.org/IAdminService/EditItemResponse")]
        System.Threading.Tasks.Task<int> EditItemAsync(int Id, string Name, string Description, float Price, string Category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : ClientApplication.AdminReference.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<ClientApplication.AdminReference.IAdminService>, ClientApplication.AdminReference.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddItem(string Name, string Description, float Price, string Category) {
            return base.Channel.AddItem(Name, Description, Price, Category);
        }
        
        public System.Threading.Tasks.Task<int> AddItemAsync(string Name, string Description, float Price, string Category) {
            return base.Channel.AddItemAsync(Name, Description, Price, Category);
        }
        
        public int DeleteItemById(int Id) {
            return base.Channel.DeleteItemById(Id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteItemByIdAsync(int Id) {
            return base.Channel.DeleteItemByIdAsync(Id);
        }
        
        public int EditItem(int Id, string Name, string Description, float Price, string Category) {
            return base.Channel.EditItem(Id, Name, Description, Price, Category);
        }
        
        public System.Threading.Tasks.Task<int> EditItemAsync(int Id, string Name, string Description, float Price, string Category) {
            return base.Channel.EditItemAsync(Id, Name, Description, Price, Category);
        }
    }
}
